f/SRV-364: Enables publishing of lambdas through CircleCI configuration
MGMDV-Orbs/microservices pull request #17
Opened 2019-03-24 03:53 UTC by patrick-sf

# PR Details

## Existing behavior
CircleCI configuration does not include commands and jobs necessary to enable publishing of lambdas.

## New intended behavior
Adds necessary CircleCI configuration to enable publishing of lambdas. 
Adds instructions on how to utilize the publish-aws-lambdas job in CircleCI configuration with each of the microservice repos.

## Description

## Where should a reviewer start?

## Related Issue/Story

## Checklist

- [x] Performed a self-review.
- [x] Assigned reviewers and set myself as Assignee
- [x] Changed a documentation ([ x ] `[ x ]` if not required).
- [x] I have added tests ([ x ] `[ x ]` if no required).

2019-03-24 04:11 UTC, afaq-sf commented on README.md
> +`main.tf` is required as the terraform entrypoint where resources are created/declared.
@patrick-sf can you please add an example of a `main.tf` file as well?
It would be helpful to have it documented.

2019-03-24 04:20 UTC, afaq-sf commented on microservices.yml
> +            npm i -g npm@latest
@patrick-sf I'm now realizing we should add a comment above this line to explain why we're updating npm.
It is to get the version of npm that supports `npm ci`

2019-03-25 13:06 UTC, misiek-sf requested changes
my main "blocker" is `@latest` version of npm; rest is "not so important"

but, i have an overall problem with all of this... we use this process with the "poc" repo and it works pretty cool for one or two lambdas but when we added 3rd and 4th then this process is unbearably long... maybe we can think about doing "one pass" terraform for all the lambdas something not like cd into each lambda and fire-up all processes of the terraform (init, plan, apply) but something like "do npm test of each lambda, pack this stuff and do only a one pass for init, plan, apply.

2019-03-25 13:06 UTC, misiek-sf commented on microservices.yml
> +            npm i -g npm@latest
@patrick-sf don't use `@latest` it will fail someday; it's better to use `@6` or so version

2019-03-25 13:06 UTC, misiek-sf commented on microservices.yml
> +            npm i -g npm@latest
or even better to use a newer version of node, as this image is using ancient `v6`?

2019-03-25 13:06 UTC, misiek-sf commented on microservices.yml
> +            npm i -g npm@latest
or maybe even better to "pack" the lambda by the "local" toolchain (not in the orb but in the "lambda" project directory itself)?

this idea comes from the lack of "test" step before publishing and if we "putting" this stuff here then it would be cool to see that we test our code before it goes to AWS...

2019-03-25 13:06 UTC, misiek-sf commented on microservices.yml
> +              if [ -e package.json ]
i know it will fail if not present... but, maybe we can check for `package-lock.json` presence before doing `npm ci` too (as both of the files are required for `npm ci` to work correctly)?

2019-03-25 13:06 UTC, misiek-sf commented on microservices.yml
> +              cd $lambdaDir/src
maybe consider using `popd/pushd` as the method of changing directories 😉

2019-03-25 23:49 UTC, afaq-sf commented on microservices.yml
> +              cd $lambdaDir/src
What is the value of doing that over this?

2019-03-26 00:53 UTC, afaq-sf commented
@moperacz @patrick-sf @tomasz-sf Couple notes per changes I made today:

1. The terraform plugins/providers installed are now cached. However, this saves less than 1 second overall. CircleCI to Terraform CDN is very fast. I've left this behavior in anyway.
2. There is now a single terraform action (per command) rather than repeated per lambda dir.
   - This saves roughly 3 to 5 seconds per lambda. Not substantial but at this point its already in there.
   - Changes required: 
      - parent `main.tf` in faas declaring "module" for each lamba
      - each lambda's `main.tf` has to manually declare its variables
      - must prefix all local paths in tf file with `${path.module}` bc terraform doesn't recommend hierarchical organizing of diff resources like this
      - terraform state stored in s3 had to be changed to single file for entire repo rather than being individual to each lambda.
   - You can see the working example on [testOrb branch of accounts repo](https://github.com/MGMResorts/accounts/tree/testOrb/faas). 
3. NVM is used to install node 8.10 to match Lambda runtime env
4. NPM is updated to 5.7 (closest version to node 8.10's npm with npm ci)

This should address all the feedback so far.

2019-03-26 11:39 UTC, misiek-sf commented on microservices.yml
> +              cd $lambdaDir/src
none whatsoever in this case

from experience; when scripting and executing "tools" often i found myself in the place that `$OLDPWD`/`$PWD` was used/manipulated by those tools and now when i see `cd -` i treat that as "antipattern" (which is not)

2019-03-26 11:41 UTC, misiek-sf approved these changes

2019-03-26 16:59 UTC, misiek-sf requested changes
sorry guys there are some things that need to be changed before merging...

1) `npm ci` should be run with NODE_ENV=production (not to install and package dev modules)
2) example of lambda in README.md should contain an example of `aws_lambda_permission`

2019-03-26 17:07 UTC, afaq-sf commented
@misiek-sf go ahead and make the change when you come across minor necessary items like this.

changing documentation + adding 2 words is more effective than blocking a PR and waiting for more paragraphs of conversation.

2019-03-27 05:40 UTC, codin-mgm submitted a review, later dismissed
Overall this looks great and I see a lot of good comments. It seems we can work on some of these items moving forward to make it "technically excellent" but if no one disagrees, should we unblock this PR?

2019-03-28 12:42 UTC, misiek-sf approved these changes

2019-03-28 19:03 UTC, afaq-sf approved these changes

2019-03-28 22:28 UTC, afaq-sf commented
@patrick-sf can you please: 
1. merge this PR
2. re-test the `testOrb` branch of accounts with the dev version of published orb
3. if #2 goes well, then publish a new release of this this orb in github and publish it to circleci with a minor version bump

let me know if I missed anything.

2019-03-29 00:44 UTC, merged